agrosite/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path,include
from django.conf.urls import url
from werobot.contrib.django import make_view
from accounts import views

from django.contrib.sitemaps.views import sitemap
from agrosite.sitemap import StaticViewSitemap, ArticleSiteMap, CategorySiteMap, TagSiteMap, UserSiteMap
from agrosite.feeds import AgrositeFeed
from django.views.decorators.cache import cache_page
import xadmin
xadmin.autodiscover()


sitemaps = {
    'blog': ArticleSiteMap,
    'Category': CategorySiteMap,
    'Tag': TagSiteMap,
    'User': UserSiteMap,
    'static': StaticViewSitemap
}

handler404 = 'blog.views.page_not_found_view'
handler500 = 'blog.views.server_error_view'
handle403 = 'blog.views.permission_denied_view'

urlpatterns = [
    # add your own patterns here
    path('admin/', xadmin.site.urls, name="admin"),
    path('mdeditor/', include('mdeditor.urls')),
    path('cookies/', include('cookie_consent.urls')),
    path('', include('notice.urls')),
    path('', include('myzone.urls')),
    path('', include('home.urls')),
    path('', include('contactus.urls')),
    path('', include('about.urls')),
    path('', include('careers.urls')),
    path('', include('services.urls')),
    path('', include('portfolio.urls')),
    path('', include('blog.urls', namespace='blog')),
    path("likes/", include("likeunlike.urls", namespace="likes")),
    path('summernote/', include('django_summernote.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    path('feed/', AgrositeFeed()),
    path('rss/', AgrositeFeed()),
    path('comment/', include('comment.urls')),
    path('notifications/', include('notifications.urls', namespace='notifications')),
    path('', include('accounts.urls', namespace='account')),
    path('search/', include('haystack.urls'), name='search'),
    path('api/', include([
        path('', include('careers.api.urls')),
    ])),
    
]
if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/about/urls.py
from django.urls import path,include
from .views import *
app_name = "about"
urlpatterns = [
    path('about/', AboutView.as_view(), name='about'),
]

apps/blog/urls.py
#!/usr/bin/env python
# encoding: utf-8


from django.urls import path
from django.views.decorators.cache import cache_page
from . import views
from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import SearchView

app_name = "blog"
urlpatterns = [
    path(r'blogs.html', views.IndexView.as_view(), name='index'),
    path(r'npage/<int:page>/', views.IndexView.as_view(), name='index_page'),

    path(r'article/<int:year>/<int:month>/<int:day>/<int:article_id>/<slug:slug>.html',
         views.ArticleDetailView.as_view(),
         name='detailbyid'),

    path(r'category/<slug:category_name>.html', views.CategoryDetailView.as_view(), name='category_detail'),
    path(r'category/<slug:category_name>/<int:page>.html', views.CategoryDetailView.as_view(),
         name='category_detail_page'),

    path(r'author/<author_name>.html', views.AuthorDetailView.as_view(), name='author_detail'),
    path(r'author/<author_name>/<int:page>.html', views.AuthorDetailView.as_view(),
         name='author_detail_page'),

    path(r'tag/<slug:tag_name>.html', views.TagDetailView.as_view(), name='tag_detail'),
    path(r'tag/<slug:tag_name>/<int:page>.html', views.TagDetailView.as_view(), name='tag_detail_page'),
    path(r'archives.html', cache_page(60 * 60)(views.ArchivesView.as_view()), name='archives'),
    path(r'links.html', views.LinkListView.as_view(), name='links'),
    path(r'upload', views.fileupload, name='upload'),
    path(r'refresh', views.refresh_memcache, name='refresh')

]

apps/home/urls.py
from django.urls import path,include
from .views import *
app_name = "home"
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

apps/notice/urls.py
from django.urls import path
from .views import *

app_name = "notice"

urlpatterns = [
    path('my_notifications/', my_notifications, name="my_notifications"),
    path('my_notification/<int:my_notifications_pk>', my_notification, name="my_notification"),
    path('delete_my_read_notifications', delete_my_read_notifications, name="delete_my_read_notifications"),
]

templates/main/connectus.html
 {% load static %}
 <!-- Say Something Start -->
        <div id="colorlib-main">
            <div class="say-something-aera pt-90 pb-90 fix">
                <div class="container">
                    <div class="row justify-content-between align-items-center">
                            <div class="offset-xl-1 offset-lg-1 col-xl-5 col-lg-5">
                                <div class="say-something-cap">
                                    <h2>Say Hello To The Collaboration Hub.</h2>
                                </div>
                            </div>
                            <div class="col-xl-2 col-lg-3">
                                <div class="say-btn">
                                    <a href="#" class="btn radius-btn">Contact Us</a>
                                </div>
                            </div>
                    </div>
                </div>
                <!-- shape -->
                <div class="say-shape">
                    <img src="{% static 'app/img/shape/say-shape-left.png' %}" alt="" class="say-shape1 rotateme d-none d-xl-block">
                    <img src="{% static 'app/img/shape/say-shape-right.png' %}" alt="" class="say-shape2 d-none d-lg-block">
                </div>
            </div>
        </div>
        <!-- Say Something End -->

templates/main/footer.html
{% load staticfiles %}
{% load blog_tags %}
 <!-- ***** Footer Area Start ***** -->
 <footer>
    <!-- Footer Start-->
      <div class="footer-main" >
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row  justify-content-between">
                    <div class="col-lg-3 col-md-4 col-sm-8">
                         <div class="single-footer-caption mb-30">
                              <!-- logo -->
                             <div class="footer-logo">
                                 <a href="index.html"><img src="{% static 'app/img/logo/logo2_footer.png' %}" alt=""></a>
                             </div>
                             <div class="footer-tittle">
                                 <div class="footer-pera">
                                     <p class="info1">Lorem ipsum dolor sit amet, consectetur adipisicing elit sed do eiusmod tempor incididunt ut labore.</p>
                                </div>
                             </div>
                         </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Quick Links</h4>
                                <ul>
                                    <li><a href="#">About</a></li>
                                    <li><a href="#">Features</a></li>
                                    <li><a href="#">Pricing</a></li>
                                    <li><a href="#">Download</a></li>
                                    <li><a href="#">Reviews</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-2 col-md-4 col-sm-7">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Support</h4>
                                <ul>
                                    <li><a href="#">Report a bug</a></li>
                                    <li><a href="#">Privacy Policy</a></li>
                                    <li><a href="#">Terms & Conditions</a></li>
                                    <li><a href="#">Sitemap</a></li>
                                    <li><a href="#">FAQs</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-8">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Newsletter</h4>
                                <div class="footer-pera footer-pera2">
                                 <p>Heaven fruitful doesn't over lesser in days. Appear </p>
                             </div>
                             <!-- Form -->
                             <div class="footer-form">
                                 <div >
                                     <form target="_blank" id="myForm" action="{% url 'contactus:newsletter' %}" method="post" class="subscribe_form relative mail_part" novalidate="true">
                                        {% csrf_token %}
                                         <input type="email" name="email" id="newsletter-form-email" placeholder=" Email Address " class="placeholder hide-on-focus" onfocus="this.placeholder = ''" onblur="this.placeholder = ' Email Address '">
                                         <div class="form-icon">
                                             <button type="submit" name="submit" id="newsletter-submit" class="email_icon submit-btn newsletter-submit button-contactForm"><img src="{% static 'app/img/shape/form_icon.png' %}" alt=""></button>
                                         </div>
                                         <div class="mt-10 alert-msg"></div>
                                     </form>
                                 </div>
                             </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Copy-Right -->
                <div class="row align-items-center">
                    <div class="col-xl-12 ">
                        <div class="footer-copy-right">
                           <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
      </div>
       <!-- Footer End-->
</footer>
<!-- ***** Footer Area End ***** -->

templates/main/header.html
{% load staticfiles %}
{% load notifications_tags %}
{% load blog_tags %}

<header>
        <!-- Header Start -->
    <div class="header-area header-transparrent ">
            <div class="main-header header-sticky">
                
                <div class="container">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2 col-md-2">
                            <div class="logo">
                                <a href="{% url 'home:home' %}"><img src="{% static 'app/img/logo/logo.png' %}" alt=""></a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10 col-md-10">
                            <!-- Main-menu -->
                            <div class="main-menu f-right d-none d-lg-block">
                                <nav>
                                    <ul id="navigation">    
                                        {% get_meanList as means %}
                                        <li class="current-item"><a href="{% url 'home:home' %}">Home</a></li>
                                        <li><a href="{% url 'about:about' %}">About</a></li>
                                        <li><a href="{% url 'blog:index' %}">Blogs</a></li>
                                        <li><a href="{% url 'services:services' %}">Services</a></li>
                                        <li><a href="{% url 'portfolio:portfolio' %}">Portfolio</a></li>
                                        <li><a href="{% url 'contactus:contact' %}">Contact</a></li>
                                        <li><a href="{% url 'careers:careers' %}">Careers</a></li>
                                    {% for mean in means %}
                                        {% if mean.status == 'y'%}
                                            <li><a href="{% url 'blog:index' %}{{ mean.link }}"><i class="menu-item-icon fa {{ mean.icon }}"></i>{{ mean.title }}</a></li>
                                        {% endif%}
                                    {% endfor %}
                                    {% if user.is_authenticated  %}
                                    <li class="">
                                        {% notifications_unread as unread_count %}
                                        <a href="{% url 'notice:my_notifications' %}"><i class="fa fa-bell" aria-hidden="true"></i>{% if unread_count %} <span class="badge">{{ unread_count }}</span>{% endif %}</a>
                                    </li>

                                    {% else %}
                                        <li class="">
                                            <a href="{% url 'accounts:login' %}?from={{ request.get_full_path }}">login/Register</a>
                                        </li>
                                    {% endif %}
                                    </ul>
                                    <div class="search-icon" data-toggle="modal" data-target="#searchModal">
                                        <i class="icon_search"></i>
                                    </div>
                                </nav>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
       </div>
        <!-- Header End -->
</header>

templates/main/load-search.html
{% load staticfiles %}
<!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <img src="{% static 'app/img/logo/logo.png' %}" alt="">
                </div>
            </div>
        </div>
    </div>
<!-- Preloader Start -->

<!-- ***** Top Search Area Start ***** -->
<div class="top-search-area">
    <!-- Search Modal -->
    <div class="modal fade" id="searchModal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-dialog-top" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <!-- Close Button -->
                    <button type="button" class="btn close-btn" data-dismiss="modal"><i class="fa fa-times"></i></button>
                    <!-- Form -->
                    <form action="{% url 'haystack_search' %}">
                        <input type="search" name="q"  placeholder="Search and hit enter..." autocomplete="off" class="form-control"/>
                        <button type="submit">Search</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
<!-- ***** Top Search Area End ***** -->

templates/main/style_switch.html
 <button type="button" data-toggle="collapse" data-target="#style-switch" id="style-switch-button" class="btn btn-primary btn-sm hidden-xs hidden-sm"><i class="fa fa-cog fa-2x"></i></button>
    <div id="style-switch" class="collapse">
      <h4 class="text-uppercase">Select theme colour</h4>
      <form class="mb-3">
        <select name="colour" id="colour" class="form-control">
          <option value="">select colour variant</option>
          <option value="default">red</option>
          <option value="pink">pink</option>
          <option value="green">green</option>
          <option value="violet">violet</option>
          <option value="sea">sea</option>
          <option value="blue">blue</option>
        </select>
      </form>
      <p><img src="https://d19m59y37dris4.cloudfront.net/jobs/2-0-2/img/template-mac.png" alt="" class="img-fluid"></p>
      <p class="text-muted text-small">Stylesheet switching is done via JavaScript and can cause a blink while page loads. This will not happen in your production code.</p>
    </div>